[package]
name = "adblock-rs"
version = "0.1.10"
authors = ["Andrius Aucinas <aaucinas@brave.com>"]
license = "MPL-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "adblock_rs"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
neon-serde = "0.1.1"
serde =  { version = "1.0", features = ["derive", "rc"] }
adblock = { path = "../" }
